# Site settings
title: Résumé
author:
  email: david@broadwater.io
  first: David Broadwater
  title: Data Scientist
  github_username:  davidbroadwater
  repository: https://github.com/davidbroadwater/resume
  website: https://github.com/davidbroadwater/resume
description: Résumé for David J. Broadwater.Top performing scientist and military veteran with 7 years of experience and a fascination with finding meaning in data. Skilled communicator with advanced technical degree and management perspective.
baseurl: "/resume/" # the subpath of your site, e.g. /blog/
url: "http://broadwater.io" # the base hostname & protocol for your site

# Compress html
compress_html:
  clippings: ['!--', html, head, title, base, link, meta, style, body, article, section, nav, aside, h1, h2, h3, h4, h5, h6, hgroup, header, footer, address, p, hr, blockquote, ol, ul, li, dl, dt, dd, figure, figcaption, main, div, table, caption, colgroup, col, tbody, thead, tfoot, tr, td, th]
  endings: [html, head, body, li, dt, dd, p, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]

# Build settings
markdown: kramdown
sass:
    style: :compressed
